The original method of extracting the data had missing sent messages. In order to grab  all messages a local iPhone backup was created. The backup is located at "~/Library/Application Support/MobileSync/Backup/". The number of folders here is dependant on how many different phones have been backed up. Inside this folder should be a folder "3d". "3d0d7e5fb2ce288813306e4d4636395e047a3d28" is the necessary file. 

A DB Browser is needed to look at the information about the database. The handle_id is needed to isolate the messages by person.

Open Terminal and type-
"sqlite3 (location of necessary file)"
 
Here is a full example-
"sqlite3 /Users/greg/Library/Application\ Support/MobileSync/Backup/0f4c9d00a4313418210fee5026491e2a628b8f5b/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28"

Access to the file should be granted. In order to export the messages to a csv file, type the following commands-

.mode csv
.output data.csv
select datetime(message.date/1000000000 + strftime("%s", "2001-01-01") ,"unixepoch","localtime"), is_from_me, text from messsage where handle_id=0;

"data.csv" is the name that the file will be saved as.
datetime(message.date/1000000000 + strftime("%s", "2001-01-01") ,"unixepoch","localtime") is necessary to grab the dates from each individual text.

In [168]:
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt

In [79]:
df = pd.read_csv('/Users/greg/Dropbox/Machine Learning/data.csv', encoding='utf8')
df.head(5)

       datetime  is_from_me                     text
0  2/8/18 22:41           0                 Anagrams
1  2/8/18 22:42           0  I've scored 1900 points
2  2/8/18 22:42           1                       �￼
3  2/8/18 22:44           0                   Aw wtf
4  2/8/18 22:44           0  I had major brain fart

In [156]:
# DATA WRANGLING
# CONVERTING DATE TO DATETIME
df['datetime'] = pd.to_datetime(df['datetime'], utc=True)
# df['datetime'] = df['datetime'].astype('datetime64[ns]')

# WORD COUNT
df['word_count'] = df['text'].str.split().str.len()

# CHECKS IF TEXT WAS A LINK
df['link'] = df['text'].str.contains('http')

# CHECKS IF TEXT CONTAINS GIF/IMAGE
df['media'] = df['text'].str.contains('�')

# GRABBING WEEKDAY, DATE, AND TIME FROM DATETIME
df['weekday'] = df['datetime'].dt.weekday
df['week'] = df['datetime'].dt.week
df['date'] = df['datetime'].dt.date
df['time'] = df['datetime'].dt.time
df['hour'] = df['datetime'].dt.hour

df.head()

                                     datetime  is_from_me  \
week time
6    22:41:00+00:00 2018-02-08 22:41:00+00:00           0
     22:42:00+00:00 2018-02-08 22:42:00+00:00           0
     22:42:00+00:00 2018-02-08 22:42:00+00:00           1
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0

                                        text  word_count   link  media  \
week time
6    22:41:00+00:00                 Anagrams         1.0  False  False
     22:42:00+00:00  I've scored 1900 points         4.0  False  False
     22:42:00+00:00                       �￼         1.0  False   True
     22:44:00+00:00                   Aw wtf         2.0  False  False
     22:44:00+00:00  I had major brain fart          5.0  False  False

                     weekday        date  hour  week            time
week time
6    22:41:00+00:00        3  2018-02-08    22     6  22:41:00+00:00
     22:42:00+00:00        3  2018-02-08    22     6  22:42:00+00:00
     22:42:00+00:00        3  2018-02-08    22     6  22:42:00+00:00
     22:44:00+00:00        3  2018-02-08    22     6  22:44:00+00:00
     22:44:00+00:00        3  2018-02-08    22     6  22:44:00+00:00

In [157]:
# df.to_csv('groupedby_data.csv', encoding='utf-8', index=False)

# CREATES MULTI-INDEX THAT ALLOWS MESSAGES TO BE GROUPED BY DATE
df.set_index(['date', 'time'], drop=False, inplace=True)

# DROPS THE COLUMNS 'DATE' AND 'TIME' BECAUSE THEY ARE BEING USED AS A MULTI-INDEX
# df.drop(['date', 'time'],axis=1, inplace=True)

df.head()

                                           datetime  is_from_me  \
date       time
2018-02-08 22:41:00+00:00 2018-02-08 22:41:00+00:00           0
           22:42:00+00:00 2018-02-08 22:42:00+00:00           0
           22:42:00+00:00 2018-02-08 22:42:00+00:00           1
           22:44:00+00:00 2018-02-08 22:44:00+00:00           0
           22:44:00+00:00 2018-02-08 22:44:00+00:00           0

                                              text  word_count   link  media  \
date       time
2018-02-08 22:41:00+00:00                 Anagrams         1.0  False  False
           22:42:00+00:00  I've scored 1900 points         4.0  False  False
           22:42:00+00:00                       �￼         1.0  False   True
           22:44:00+00:00                   Aw wtf         2.0  False  False
           22:44:00+00:00  I had major brain fart          5.0  False  False

                           weekday        date  hour  week            time
date       time
2018-02-08 22:41:00+00:00        3  2018-02-08    22     6  22:41:00+00:00
           22:42:00+00:00        3  2018-02-08    22     6  22:42:00+00:00
           22:42:00+00:00        3  2018-02-08    22     6  22:42:00+00:00
           22:44:00+00:00        3  2018-02-08    22     6  22:44:00+00:00
           22:44:00+00:00        3  2018-02-08    22     6  22:44:00+00:00

In [92]:
days = df['date'].unique()
days

array([datetime.date(2018, 2, 8), datetime.date(2018, 2, 9),
       datetime.date(2018, 2, 10), datetime.date(2018, 2, 12),
       datetime.date(2018, 2, 13), datetime.date(2018, 2, 14),
       datetime.date(2018, 2, 15), datetime.date(2018, 2, 16),
       datetime.date(2018, 2, 17), datetime.date(2018, 2, 18),
       datetime.date(2018, 2, 19), datetime.date(2018, 2, 20),
       datetime.date(2018, 2, 21), datetime.date(2018, 2, 22),
       datetime.date(2018, 2, 23), datetime.date(2018, 2, 24),
       datetime.date(2018, 2, 25), datetime.date(2018, 2, 26),
       datetime.date(2018, 2, 27), datetime.date(2018, 2, 28),
       datetime.date(2018, 3, 1), datetime.date(2018, 3, 2),
       datetime.date(2018, 3, 3), datetime.date(2018, 3, 4),
       datetime.date(2018, 3, 5), datetime.date(2018, 3, 6),
       datetime.date(2018, 3, 7), datetime.date(2018, 3, 8),
       datetime.date(2018, 3, 9), datetime.date(2018, 3, 10),
       datetime.date(2018, 3, 11), datetime.date(2018, 3, 12),
       datetime.date(2018, 3, 13), datetime.date(2018, 3, 14),
       datetime.date(2018, 3, 15), datetime.date(2018, 3, 16),
       datetime.date(2018, 3, 17), datetime.date(2018, 3, 18),
       datetime.date(2018, 3, 19), datetime.date(2018, 3, 20),
       datetime.date(2018, 3, 21), datetime.date(2018, 3, 22),
       datetime.date(2018, 3, 23), datetime.date(2018, 3, 24),
       datetime.date(2018, 3, 25), datetime.date(2018, 3, 26),
       datetime.date(2018, 3, 27), datetime.date(2018, 3, 28),
       datetime.date(2018, 3, 29), datetime.date(2018, 3, 30),
       datetime.date(2018, 3, 31), datetime.date(2018, 4, 1),
       datetime.date(2018, 4, 2), datetime.date(2018, 4, 3),
       datetime.date(2018, 4, 4), datetime.date(2018, 4, 5),
       datetime.date(2018, 4, 6), datetime.date(2018, 4, 7),
       datetime.date(2018, 4, 8), datetime.date(2018, 4, 9),
       datetime.date(2018, 4, 10), datetime.date(2018, 4, 11),
       datetime.date(2018, 4, 12), datetime.date(2018, 4, 13),
       datetime.date(2018, 4, 14), datetime.date(2018, 4, 15),
       datetime.date(2018, 4, 16), datetime.date(2018, 4, 17),
       datetime.date(2018, 4, 18), datetime.date(2018, 4, 19),
       datetime.date(2018, 4, 20), datetime.date(2018, 4, 21),
       datetime.date(2018, 4, 22), datetime.date(2018, 4, 23),
       datetime.date(2018, 4, 24), datetime.date(2018, 4, 25),
       datetime.date(2018, 4, 26), datetime.date(2018, 4, 27),
       datetime.date(2018, 4, 28), datetime.date(2018, 4, 29),
       datetime.date(2018, 4, 30), datetime.date(2018, 5, 1),
       datetime.date(2018, 5, 2), datetime.date(2018, 5, 3),
       datetime.date(2018, 5, 4), datetime.date(2018, 5, 5),
       datetime.date(2018, 5, 6), datetime.date(2018, 5, 7),
       datetime.date(2018, 5, 8), datetime.date(2018, 5, 9),
       datetime.date(2018, 5, 10), datetime.date(2018, 5, 11),
       datetime.date(2018, 5, 12), datetime.date(2018, 5, 13),
       datetime.date(2018, 5, 14), datetime.date(2018, 5, 15),
       datetime.date(2018, 5, 16), datetime.date(2018, 5, 17),
       datetime.date(2018, 5, 18), datetime.date(2018, 5, 19),
       datetime.date(2018, 5, 21), datetime.date(2018, 5, 22),
       datetime.date(2018, 5, 23), datetime.date(2018, 5, 24),
       datetime.date(2018, 5, 25), datetime.date(2018, 5, 26),
       datetime.date(2018, 5, 27), datetime.date(2018, 5, 28),
       datetime.date(2018, 5, 29), datetime.date(2018, 5, 30),
       datetime.date(2018, 5, 31), datetime.date(2018, 6, 1),
       datetime.date(2018, 6, 2), datetime.date(2018, 6, 3),
       datetime.date(2018, 6, 4), datetime.date(2018, 6, 5),
       datetime.date(2018, 6, 6), datetime.date(2018, 6, 7),
       datetime.date(2018, 6, 8), datetime.date(2018, 6, 9),
       datetime.date(2018, 6, 10), datetime.date(2018, 6, 11),
       datetime.date(2018, 6, 12), datetime.date(2018, 6, 13),
       datetime.date(2018, 6, 14), datetime.date(2018, 6, 15),
       datetime.date(2018, 6, 16), datetime.date(2018, 6, 17),
       datetime.date(2018, 6, 18), datetime.date(2018, 6, 19),
       datetime.date(2018, 6, 20), datetime.date(2018, 6, 21),
       datetime.date(2018, 6, 22), datetime.date(2018, 6, 23),
       datetime.date(2018, 6, 24), datetime.date(2018, 6, 25),
       datetime.date(2018, 6, 26), datetime.date(2018, 6, 27),
       datetime.date(2018, 6, 28), datetime.date(2018, 6, 29),
       datetime.date(2018, 6, 30), datetime.date(2018, 7, 1),
       datetime.date(2018, 7, 2), datetime.date(2018, 7, 3),
       datetime.date(2018, 7, 4), datetime.date(2018, 7, 5),
       datetime.date(2018, 7, 6), datetime.date(2018, 7, 7),
       datetime.date(2018, 7, 8), datetime.date(2018, 7, 9),
       datetime.date(2018, 7, 10), datetime.date(2018, 7, 11),
       datetime.date(2018, 7, 12), datetime.date(2018, 7, 13),
       datetime.date(2018, 7, 14), datetime.date(2018, 7, 15),
       datetime.date(2018, 7, 16), datetime.date(2018, 7, 17),
       datetime.date(2018, 7, 18), datetime.date(2018, 7, 19),
       datetime.date(2018, 7, 20), datetime.date(2018, 7, 21),
       datetime.date(2018, 7, 22), datetime.date(2018, 7, 23),
       datetime.date(2018, 7, 24), datetime.date(2018, 7, 25),
       datetime.date(2018, 7, 26), datetime.date(2018, 7, 27),
       datetime.date(2018, 7, 28), datetime.date(2018, 7, 29),
       datetime.date(2018, 7, 30), datetime.date(2018, 7, 31),
       datetime.date(2018, 8, 1), datetime.date(2018, 8, 2),
       datetime.date(2018, 8, 3), datetime.date(2018, 8, 4),
       datetime.date(2018, 8, 5), datetime.date(2018, 8, 6),
       datetime.date(2018, 8, 7), datetime.date(2018, 8, 8),
       datetime.date(2018, 8, 9), datetime.date(2018, 8, 10),
       datetime.date(2018, 8, 11), datetime.date(2018, 8, 12),
       datetime.date(2018, 8, 13), datetime.date(2018, 8, 14),
       datetime.date(2018, 8, 15), datetime.date(2018, 8, 16),
       datetime.date(2018, 8, 17)], dtype=object)

In [93]:
df['date'].nunique()
# n_days

189

In [58]:
df['date'].min()
# start_date

datetime.date(2018, 2, 8)

In [123]:
df['date'].max()
# end_date

datetime.date(2018, 8, 17)

In [94]:
n_texts = {}
for d in days:
    n_texts[d] = len(df.loc[d])

n_texts

{datetime.date(2018, 2, 8): 70,
 datetime.date(2018, 2, 9): 273,
 datetime.date(2018, 2, 10): 96,
 datetime.date(2018, 2, 12): 105,
 datetime.date(2018, 2, 13): 632,
 datetime.date(2018, 2, 14): 629,
 datetime.date(2018, 2, 15): 103,
 datetime.date(2018, 2, 16): 322,
 datetime.date(2018, 2, 17): 1128,
 datetime.date(2018, 2, 18): 175,
 datetime.date(2018, 2, 19): 709,
 datetime.date(2018, 2, 20): 628,
 datetime.date(2018, 2, 21): 395,
 datetime.date(2018, 2, 22): 728,
 datetime.date(2018, 2, 23): 468,
 datetime.date(2018, 2, 24): 427,
 datetime.date(2018, 2, 25): 162,
 datetime.date(2018, 2, 26): 366,
 datetime.date(2018, 2, 27): 433,
 datetime.date(2018, 2, 28): 314,
 datetime.date(2018, 3, 1): 64,
 datetime.date(2018, 3, 2): 641,
 datetime.date(2018, 3, 3): 603,
 datetime.date(2018, 3, 4): 869,
 datetime.date(2018, 3, 5): 298,
 datetime.date(2018, 3, 6): 453,
 datetime.date(2018, 3, 7): 522,
 datetime.date(2018, 3, 8): 560,
 datetime.date(2018, 3, 9): 642,
 datetime.date(2018, 3, 10): 911,
 datetime.date(2018, 3, 11): 462,
 datetime.date(2018, 3, 12): 342,
 datetime.date(2018, 3, 13): 507,
 datetime.date(2018, 3, 14): 631,
 datetime.date(2018, 3, 15): 246,
 datetime.date(2018, 3, 16): 450,
 datetime.date(2018, 3, 17): 312,
 datetime.date(2018, 3, 18): 269,
 datetime.date(2018, 3, 19): 469,
 datetime.date(2018, 3, 20): 584,
 datetime.date(2018, 3, 21): 329,
 datetime.date(2018, 3, 22): 679,
 datetime.date(2018, 3, 23): 464,
 datetime.date(2018, 3, 24): 420,
 datetime.date(2018, 3, 25): 334,
 datetime.date(2018, 3, 26): 447,
 datetime.date(2018, 3, 27): 406,
 datetime.date(2018, 3, 28): 626,
 datetime.date(2018, 3, 29): 338,
 datetime.date(2018, 3, 30): 511,
 datetime.date(2018, 3, 31): 348,
 datetime.date(2018, 4, 1): 279,
 datetime.date(2018, 4, 2): 445,
 datetime.date(2018, 4, 3): 430,
 datetime.date(2018, 4, 4): 337,
 datetime.date(2018, 4, 5): 407,
 datetime.date(2018, 4, 6): 398,
 datetime.date(2018, 4, 7): 225,
 datetime.date(2018, 4, 8): 356,
 datetime.date(2018, 4, 9): 187,
 datetime.date(2018, 4, 10): 524,
 datetime.date(2018, 4, 11): 189,
 datetime.date(2018, 4, 12): 299,
 datetime.date(2018, 4, 13): 169,
 datetime.date(2018, 4, 14): 877,
 datetime.date(2018, 4, 15): 473,
 datetime.date(2018, 4, 16): 293,
 datetime.date(2018, 4, 17): 992,
 datetime.date(2018, 4, 18): 471,
 datetime.date(2018, 4, 19): 556,
 datetime.date(2018, 4, 20): 363,
 datetime.date(2018, 4, 21): 179,
 datetime.date(2018, 4, 22): 537,
 datetime.date(2018, 4, 23): 430,
 datetime.date(2018, 4, 24): 499,
 datetime.date(2018, 4, 25): 202,
 datetime.date(2018, 4, 26): 300,
 datetime.date(2018, 4, 27): 290,
 datetime.date(2018, 4, 28): 466,
 datetime.date(2018, 4, 29): 379,
 datetime.date(2018, 4, 30): 448,
 datetime.date(2018, 5, 1): 243,
 datetime.date(2018, 5, 2): 327,
 datetime.date(2018, 5, 3): 248,
 datetime.date(2018, 5, 4): 366,
 datetime.date(2018, 5, 5): 579,
 datetime.date(2018, 5, 6): 302,
 datetime.date(2018, 5, 7): 330,
 datetime.date(2018, 5, 8): 197,
 datetime.date(2018, 5, 9): 152,
 datetime.date(2018, 5, 10): 160,
 datetime.date(2018, 5, 11): 223,
 datetime.date(2018, 5, 12): 346,
 datetime.date(2018, 5, 13): 475,
 datetime.date(2018, 5, 14): 266,
 datetime.date(2018, 5, 15): 257,
 datetime.date(2018, 5, 16): 495,
 datetime.date(2018, 5, 17): 293,
 datetime.date(2018, 5, 18): 251,
 datetime.date(2018, 5, 19): 331,
 datetime.date(2018, 5, 21): 14,
 datetime.date(2018, 5, 22): 163,
 datetime.date(2018, 5, 23): 272,
 datetime.date(2018, 5, 24): 143,
 datetime.date(2018, 5, 25): 187,
 datetime.date(2018, 5, 26): 167,
 datetime.date(2018, 5, 27): 196,
 datetime.date(2018, 5, 28): 234,
 datetime.date(2018, 5, 29): 182,
 datetime.date(2018, 5, 30): 435,
 datetime.date(2018, 5, 31): 185,
 datetime.date(2018, 6, 1): 97,
 datetime.date(2018, 6, 2): 296,
 datetime.date(2018, 6, 3): 278,
 datetime.date(2018, 6, 4): 208,
 datetime.date(2018, 6, 5): 200,
 datetime.date(2018, 6, 6): 363,
 datetime.date(2018, 6, 7): 235,
 datetime.date(2018, 6, 8): 239,
 datetime.date(2018, 6, 9): 312,
 datetime.date(2018, 6, 10): 301,
 datetime.date(2018, 6, 11): 267,
 datetime.date(2018, 6, 12): 195,
 datetime.date(2018, 6, 13): 444,
 datetime.date(2018, 6, 14): 352,
 datetime.date(2018, 6, 15): 221,
 datetime.date(2018, 6, 16): 205,
 datetime.date(2018, 6, 17): 537,
 datetime.date(2018, 6, 18): 280,
 datetime.date(2018, 6, 19): 461,
 datetime.date(2018, 6, 20): 454,
 datetime.date(2018, 6, 21): 448,
 datetime.date(2018, 6, 22): 601,
 datetime.date(2018, 6, 23): 221,
 datetime.date(2018, 6, 24): 499,
 datetime.date(2018, 6, 25): 399,
 datetime.date(2018, 6, 26): 427,
 datetime.date(2018, 6, 27): 484,
 datetime.date(2018, 6, 28): 245,
 datetime.date(2018, 6, 29): 107,
 datetime.date(2018, 6, 30): 208,
 datetime.date(2018, 7, 1): 417,
 datetime.date(2018, 7, 2): 503,
 datetime.date(2018, 7, 3): 263,
 datetime.date(2018, 7, 4): 137,
 datetime.date(2018, 7, 5): 306,
 datetime.date(2018, 7, 6): 356,
 datetime.date(2018, 7, 7): 306,
 datetime.date(2018, 7, 8): 197,
 datetime.date(2018, 7, 9): 86,
 datetime.date(2018, 7, 10): 150,
 datetime.date(2018, 7, 11): 73,
 datetime.date(2018, 7, 12): 134,
 datetime.date(2018, 7, 13): 333,
 datetime.date(2018, 7, 14): 49,
 datetime.date(2018, 7, 15): 394,
 datetime.date(2018, 7, 16): 223,
 datetime.date(2018, 7, 17): 275,
 datetime.date(2018, 7, 18): 275,
 datetime.date(2018, 7, 19): 222,
 datetime.date(2018, 7, 20): 162,
 datetime.date(2018, 7, 21): 379,
 datetime.date(2018, 7, 22): 158,
 datetime.date(2018, 7, 23): 64,
 datetime.date(2018, 7, 24): 422,
 datetime.date(2018, 7, 25): 255,
 datetime.date(2018, 7, 26): 324,
 datetime.date(2018, 7, 27): 104,
 datetime.date(2018, 7, 28): 114,
 datetime.date(2018, 7, 29): 387,
 datetime.date(2018, 7, 30): 168,
 datetime.date(2018, 7, 31): 15,
 datetime.date(2018, 8, 1): 42,
 datetime.date(2018, 8, 2): 99,
 datetime.date(2018, 8, 3): 4,
 datetime.date(2018, 8, 4): 332,
 datetime.date(2018, 8, 5): 462,
 datetime.date(2018, 8, 6): 297,
 datetime.date(2018, 8, 7): 274,
 datetime.date(2018, 8, 8): 396,
 datetime.date(2018, 8, 9): 247,
 datetime.date(2018, 8, 10): 529,
 datetime.date(2018, 8, 11): 581,
 datetime.date(2018, 8, 12): 132,
 datetime.date(2018, 8, 13): 337,
 datetime.date(2018, 8, 14): 215,
 datetime.date(2018, 8, 15): 88,
 datetime.date(2018, 8, 16): 334,
 datetime.date(2018, 8, 17): 101}

In [180]:
greg = df[df['is_from_me']==1]
greg.head()

                                     datetime  is_from_me  \
week time
6    22:42:00+00:00 2018-02-08 22:42:00+00:00           1
     22:44:00+00:00 2018-02-08 22:44:00+00:00           1
     22:44:00+00:00 2018-02-08 22:44:00+00:00           1
     22:46:00+00:00 2018-02-08 22:46:00+00:00           1
     22:50:00+00:00 2018-02-08 22:50:00+00:00           1

                                                 text  word_count   link  \
week time
6    22:42:00+00:00                                �￼         1.0  False
     22:44:00+00:00                              Lmao         1.0  False
     22:44:00+00:00  You thought it was gonna be easy         7.0  False
     22:46:00+00:00                          Anagrams         1.0  False
     22:50:00+00:00                                �￼         1.0  False

                     media  weekday        date  hour  week            time
week time
6    22:42:00+00:00   True        3  2018-02-08    22     6  22:42:00+00:00
     22:44:00+00:00  False        3  2018-02-08    22     6  22:44:00+00:00
     22:44:00+00:00  False        3  2018-02-08    22     6  22:44:00+00:00
     22:46:00+00:00  False        3  2018-02-08    22     6  22:46:00+00:00
     22:50:00+00:00   True        3  2018-02-08    22     6  22:50:00+00:00

In [181]:
emily = df[df['is_from_me']==0]
emily.head()

                                     datetime  is_from_me  \
week time
6    22:41:00+00:00 2018-02-08 22:41:00+00:00           0
     22:42:00+00:00 2018-02-08 22:42:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0

                                                  text  word_count   link  \
week time
6    22:41:00+00:00                           Anagrams         1.0  False
     22:42:00+00:00            I've scored 1900 points         4.0  False
     22:44:00+00:00                             Aw wtf         2.0  False
     22:44:00+00:00            I had major brain fart          5.0  False
     22:44:00+00:00  That wasn't even a fart actually          6.0  False

                     media  weekday        date  hour  week            time
week time
6    22:41:00+00:00  False        3  2018-02-08    22     6  22:41:00+00:00
     22:42:00+00:00  False        3  2018-02-08    22     6  22:42:00+00:00
     22:44:00+00:00  False        3  2018-02-08    22     6  22:44:00+00:00
     22:44:00+00:00  False        3  2018-02-08    22     6  22:44:00+00:00
     22:44:00+00:00  False        3  2018-02-08    22     6  22:44:00+00:00

In [179]:
max_texts = max(n_texts.values())
min_texts = min(n_texts.values())
max_text_day = [k for k, v in n_texts.items() if v == max_texts]
min_text_day = [k for k, v in n_texts.items() if v == min_texts]

print(max_text_day, max_texts)
print(min_text_day, min_texts)

[datetime.date(2018, 2, 17)] 1128
[datetime.date(2018, 8, 3)] 4

In [129]:
df['hour'].value_counts().sort_index()
# hour_usage

0     5398
1     2489
2     1290
3      312
4       27
5       33
6       50
7      188
8     1865
9     2897
10    2560
11    2899
12    2994
13    3050
14    2823
15    3153
16    2288
17    2849
18    3218
19    3530
20    3642
21    4798
22    5860
23    6011
Name: hour, dtype: int64

In [124]:
df['hour'].value_counts().sort_index()/df['date'].nunique()
# hour_usage/n_days
# text_per_hour

0     28.560847
1     13.169312
2      6.825397
3      1.650794
4      0.142857
5      0.174603
6      0.264550
7      0.994709
8      9.867725
9     15.328042
10    13.544974
11    15.338624
12    15.841270
13    16.137566
14    14.936508
15    16.682540
16    12.105820
17    15.074074
18    17.026455
19    18.677249
20    19.269841
21    25.386243
22    31.005291
23    31.804233
Name: hour, dtype: float64

In [130]:
df['weekday'].value_counts().sort_index()

0     8215
1    10027
2     9337
3     8325
4     8872
5    10418
6     9030
Name: weekday, dtype: int64

In [160]:
df.set_index(['week','time'], drop=False, inplace=True)

                                     datetime  is_from_me  \
week time
6    22:41:00+00:00 2018-02-08 22:41:00+00:00           0
     22:42:00+00:00 2018-02-08 22:42:00+00:00           0
     22:42:00+00:00 2018-02-08 22:42:00+00:00           1
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           1
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:44:00+00:00 2018-02-08 22:44:00+00:00           1
     22:44:00+00:00 2018-02-08 22:44:00+00:00           0
     22:46:00+00:00 2018-02-08 22:46:00+00:00           1
     22:48:00+00:00 2018-02-08 22:48:00+00:00           0
     22:48:00+00:00 2018-02-08 22:48:00+00:00           0
     22:50:00+00:00 2018-02-08 22:50:00+00:00           1
     22:50:00+00:00 2018-02-08 22:50:00+00:00           1
     22:50:00+00:00 2018-02-08 22:50:00+00:00           0
     22:51:00+00:00 2018-02-08 22:51:00+00:00           1
     22:51:00+00:00 2018-02-08 22:51:00+00:00           0
     22:51:00+00:00 2018-02-08 22:51:00+00:00           0
     22:51:00+00:00 2018-02-08 22:51:00+00:00           0
     22:56:00+00:00 2018-02-08 22:56:00+00:00           1
     22:57:00+00:00 2018-02-08 22:57:00+00:00           1
     22:58:00+00:00 2018-02-08 22:58:00+00:00           0
     22:59:00+00:00 2018-02-08 22:59:00+00:00           1
     22:59:00+00:00 2018-02-08 22:59:00+00:00           0
     23:00:00+00:00 2018-02-08 23:00:00+00:00           1
     23:00:00+00:00 2018-02-08 23:00:00+00:00           0
     23:01:00+00:00 2018-02-08 23:01:00+00:00           0
     23:02:00+00:00 2018-02-08 23:02:00+00:00           1
     23:03:00+00:00 2018-02-08 23:03:00+00:00           1
...                                       ...         ...
33   11:10:00+00:00 2018-08-17 11:10:00+00:00           1
     11:10:00+00:00 2018-08-17 11:10:00+00:00           0
     11:11:00+00:00 2018-08-17 11:11:00+00:00           0
     11:11:00+00:00 2018-08-17 11:11:00+00:00           0
     11:51:00+00:00 2018-08-17 11:51:00+00:00           1
     11:51:00+00:00 2018-08-17 11:51:00+00:00           1
     12:02:00+00:00 2018-08-17 12:02:00+00:00           0
     12:51:00+00:00 2018-08-17 12:51:00+00:00           1
     12:51:00+00:00 2018-08-17 12:51:00+00:00           0
     12:51:00+00:00 2018-08-17 12:51:00+00:00           1
     12:52:00+00:00 2018-08-17 12:52:00+00:00           0
     12:56:00+00:00 2018-08-17 12:56:00+00:00           1
     12:56:00+00:00 2018-08-17 12:56:00+00:00           0
     13:00:00+00:00 2018-08-17 13:00:00+00:00           1
     13:00:00+00:00 2018-08-17 13:00:00+00:00           1
     13:00:00+00:00 2018-08-17 13:00:00+00:00           1
     13:01:00+00:00 2018-08-17 13:01:00+00:00           0
     13:01:00+00:00 2018-08-17 13:01:00+00:00           1
     13:01:00+00:00 2018-08-17 13:01:00+00:00           1
     13:01:00+00:00 2018-08-17 13:01:00+00:00           1
     13:01:00+00:00 2018-08-17 13:01:00+00:00           0
     13:01:00+00:00 2018-08-17 13:01:00+00:00           1
     13:01:00+00:00 2018-08-17 13:01:00+00:00           0
     13:01:00+00:00 2018-08-17 13:01:00+00:00           0
     13:01:00+00:00 2018-08-17 13:01:00+00:00           0
     13:11:00+00:00 2018-08-17 13:11:00+00:00           1
     13:12:00+00:00 2018-08-17 13:12:00+00:00           0
     13:36:00+00:00 2018-08-17 13:36:00+00:00           0
     13:36:00+00:00 2018-08-17 13:36:00+00:00           1
     14:03:00+00:00 2018-08-17 14:03:00+00:00           0

                                                                  text  \
week time
6    22:41:00+00:00                                           Anagrams
     22:42:00+00:00                            I've scored 1900 points
     22:42:00+00:00                                                 �￼
     22:44:00+00:00                                             Aw wtf
     22:44:00+00:00                            I had major brain fart
     22:44:00+00:00                                               Lmao
     22:44:00+00:00                  That wasn't even a fart actually
     22:44:00+00:00                                  More like a shit
     22:44:00+00:00                   You thought it was gonna be easy
     22:44:00+00:00                              I underestimated you
     22:46:00+00:00                                           Anagrams
     22:48:00+00:00                            I've scored 1800 points
     22:48:00+00:00                           Who even likes anagrams
     22:50:00+00:00                                                 �￼
     22:50:00+00:00                   You're the one who started it lo
     22:50:00+00:00         Wow you should actually play against John
     22:51:00+00:00                        Why cause we’re both asian?
     22:51:00+00:00                                            Lmaooo
     22:51:00+00:00                                         Well duuuh
     22:51:00+00:00                No cause pretty good at it too aha
     22:56:00+00:00                                           Anagrams
     22:57:00+00:00                              Maybe this will help
     22:58:00+00:00                             I've scored 800 points
     22:59:00+00:00                                                 �￼
     22:59:00+00:00  ￼Wtf I kept putting words in and it kept say "...
     23:00:00+00:00                             That was actually hard
     23:00:00+00:00                       That wasn't even Spanish aha
     23:01:00+00:00                Stupid iPhone doesn't know Spanish
     23:02:00+00:00  Maybe you have to set Spanish as the default l...
     23:03:00+00:00                                    Like what I did
...                                                                ...
33   11:10:00+00:00                         People make mistakes babe
     11:10:00+00:00                 Trying to shame me for not reason
     11:11:00+00:00                                          Ahahahaha
     11:11:00+00:00                                                No*
     11:51:00+00:00                                         Qué haces
     11:51:00+00:00                      Want to FaceTime really quick
     12:02:00+00:00                                          MWUAHAHA
     12:51:00+00:00                                      I’ve been had
     12:51:00+00:00                                                Why
     12:51:00+00:00  You got me with the “LeTs SeE wHo HaNgS uP fIrSt”
     12:52:00+00:00                           Omg ahaha all late babe
     12:56:00+00:00        I’m just waiting for the laundry to be done
     12:56:00+00:00                            Yay you’re almost done
     13:00:00+00:00                             That was just one load
     13:00:00+00:00                                     I have 4 total
     13:00:00+00:00                  I don’t know what to wear tonight
     13:01:00+00:00            Well i think I might wear that lacy top
     13:01:00+00:00                                               BABE
     13:01:00+00:00                                     You’re armpits
     13:01:00+00:00                             We have to tweeze them
     13:01:00+00:00                                               Omg
     13:01:00+00:00                             Or are you gonna shave
     13:01:00+00:00                                      You’re right
     13:01:00+00:00   Well if you’re not able to them I’ll just shave
     13:01:00+00:00                                              Then*
     13:11:00+00:00                    I’m gonna shower then head over
     13:12:00+00:00                                          Okay babe
     13:36:00+00:00                                     Aha I let you
     13:36:00+00:00                                          Sure babe
     14:03:00+00:00                                        I did babe

                     word_count   link  media  weekday        date  hour  \
week time
6    22:41:00+00:00         1.0  False  False        3  2018-02-08    22
     22:42:00+00:00         4.0  False  False        3  2018-02-08    22
     22:42:00+00:00         1.0  False   True        3  2018-02-08    22
     22:44:00+00:00         2.0  False  False        3  2018-02-08    22
     22:44:00+00:00         5.0  False  False        3  2018-02-08    22
     22:44:00+00:00         1.0  False  False        3  2018-02-08    22
     22:44:00+00:00         6.0  False  False        3  2018-02-08    22
     22:44:00+00:00         4.0  False  False        3  2018-02-08    22
     22:44:00+00:00         7.0  False  False        3  2018-02-08    22
     22:44:00+00:00         3.0  False  False        3  2018-02-08    22
     22:46:00+00:00         1.0  False  False        3  2018-02-08    22
     22:48:00+00:00         4.0  False  False        3  2018-02-08    22
     22:48:00+00:00         4.0  False  False        3  2018-02-08    22
     22:50:00+00:00         1.0  False   True        3  2018-02-08    22
     22:50:00+00:00         7.0  False  False        3  2018-02-08    22
     22:50:00+00:00         7.0  False  False        3  2018-02-08    22
     22:51:00+00:00         5.0  False  False        3  2018-02-08    22
     22:51:00+00:00         1.0  False  False        3  2018-02-08    22
     22:51:00+00:00         2.0  False  False        3  2018-02-08    22
     22:51:00+00:00         8.0  False  False        3  2018-02-08    22
     22:56:00+00:00         1.0  False  False        3  2018-02-08    22
     22:57:00+00:00         4.0  False  False        3  2018-02-08    22
     22:58:00+00:00         4.0  False  False        3  2018-02-08    22
     22:59:00+00:00         1.0  False   True        3  2018-02-08    22
     22:59:00+00:00        13.0  False  False        3  2018-02-08    22
     23:00:00+00:00         4.0  False  False        3  2018-02-08    23
     23:00:00+00:00         5.0  False  False        3  2018-02-08    23
     23:01:00+00:00         5.0  False  False        3  2018-02-08    23
     23:02:00+00:00        10.0  False  False        3  2018-02-08    23
     23:03:00+00:00         4.0  False  False        3  2018-02-08    23
...                         ...    ...    ...      ...         ...   ...
33   11:10:00+00:00         4.0  False  False        4  2018-08-17    11
     11:10:00+00:00         7.0  False  False        4  2018-08-17    11
     11:11:00+00:00         1.0  False  False        4  2018-08-17    11
     11:11:00+00:00         1.0  False  False        4  2018-08-17    11
     11:51:00+00:00         2.0  False  False        4  2018-08-17    11
     11:51:00+00:00         5.0  False  False        4  2018-08-17    11
     12:02:00+00:00         1.0  False  False        4  2018-08-17    12
     12:51:00+00:00         3.0  False  False        4  2018-08-17    12
     12:51:00+00:00         1.0  False  False        4  2018-08-17    12
     12:51:00+00:00        11.0  False  False        4  2018-08-17    12
     12:52:00+00:00         5.0  False  False        4  2018-08-17    12
     12:56:00+00:00         9.0  False  False        4  2018-08-17    12
     12:56:00+00:00         4.0  False  False        4  2018-08-17    12
     13:00:00+00:00         5.0  False  False        4  2018-08-17    13
     13:00:00+00:00         4.0  False  False        4  2018-08-17    13
     13:00:00+00:00         7.0  False  False        4  2018-08-17    13
     13:01:00+00:00         9.0  False  False        4  2018-08-17    13
     13:01:00+00:00         1.0  False  False        4  2018-08-17    13
     13:01:00+00:00         2.0  False  False        4  2018-08-17    13
     13:01:00+00:00         5.0  False  False        4  2018-08-17    13
     13:01:00+00:00         1.0  False  False        4  2018-08-17    13
     13:01:00+00:00         5.0  False  False        4  2018-08-17    13
     13:01:00+00:00         2.0  False  False        4  2018-08-17    13
     13:01:00+00:00        10.0  False  False        4  2018-08-17    13
     13:01:00+00:00         1.0  False  False        4  2018-08-17    13
     13:11:00+00:00         6.0  False  False        4  2018-08-17    13
     13:12:00+00:00         2.0  False  False        4  2018-08-17    13
     13:36:00+00:00         4.0  False  False        4  2018-08-17    13
     13:36:00+00:00         2.0  False  False        4  2018-08-17    13
     14:03:00+00:00         3.0  False  False        4  2018-08-17    14

                     week            time
week time
6    22:41:00+00:00     6  22:41:00+00:00
     22:42:00+00:00     6  22:42:00+00:00
     22:42:00+00:00     6  22:42:00+00:00
     22:44:00+00:00     6  22:44:00+00:00
     22:44:00+00:00     6  22:44:00+00:00
     22:44:00+00:00     6  22:44:00+00:00
     22:44:00+00:00     6  22:44:00+00:00
     22:44:00+00:00     6  22:44:00+00:00
     22:44:00+00:00     6  22:44:00+00:00
     22:44:00+00:00     6  22:44:00+00:00
     22:46:00+00:00     6  22:46:00+00:00
     22:48:00+00:00     6  22:48:00+00:00
     22:48:00+00:00     6  22:48:00+00:00
     22:50:00+00:00     6  22:50:00+00:00
     22:50:00+00:00     6  22:50:00+00:00
     22:50:00+00:00     6  22:50:00+00:00
     22:51:00+00:00     6  22:51:00+00:00
     22:51:00+00:00     6  22:51:00+00:00
     22:51:00+00:00     6  22:51:00+00:00
     22:51:00+00:00     6  22:51:00+00:00
     22:56:00+00:00     6  22:56:00+00:00
     22:57:00+00:00     6  22:57:00+00:00
     22:58:00+00:00     6  22:58:00+00:00
     22:59:00+00:00     6  22:59:00+00:00
     22:59:00+00:00     6  22:59:00+00:00
     23:00:00+00:00     6  23:00:00+00:00
     23:00:00+00:00     6  23:00:00+00:00
     23:01:00+00:00     6  23:01:00+00:00
     23:02:00+00:00     6  23:02:00+00:00
     23:03:00+00:00     6  23:03:00+00:00
...                   ...             ...
33   11:10:00+00:00    33  11:10:00+00:00
     11:10:00+00:00    33  11:10:00+00:00
     11:11:00+00:00    33  11:11:00+00:00
     11:11:00+00:00    33  11:11:00+00:00
     11:51:00+00:00    33  11:51:00+00:00
     11:51:00+00:00    33  11:51:00+00:00
     12:02:00+00:00    33  12:02:00+00:00
     12:51:00+00:00    33  12:51:00+00:00
     12:51:00+00:00    33  12:51:00+00:00
     12:51:00+00:00    33  12:51:00+00:00
     12:52:00+00:00    33  12:52:00+00:00
     12:56:00+00:00    33  12:56:00+00:00
     12:56:00+00:00    33  12:56:00+00:00
     13:00:00+00:00    33  13:00:00+00:00
     13:00:00+00:00    33  13:00:00+00:00
     13:00:00+00:00    33  13:00:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:01:00+00:00    33  13:01:00+00:00
     13:11:00+00:00    33  13:11:00+00:00
     13:12:00+00:00    33  13:12:00+00:00
     13:36:00+00:00    33  13:36:00+00:00
     13:36:00+00:00    33  13:36:00+00:00
     14:03:00+00:00    33  14:03:00+00:00

[64224 rows x 11 columns]

In [172]:
weeks = np.arange(df['week'].min(), df['week'].max())
weeks

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [173]:
weekly_change = {}
for w in weeks:
    weekday_change[w] = len(df.loc[w])
    
weekly_change

{}